SEED = 20260901
SOURCE_DATE_EPOCH = "1788220800"

PROJECT = "Notely"
AUDIT_DATE = "01 de setembro de 2026"
SCOPE = (
    "Aplicacao SaaS de notas e espacos colaborativos - backend Express/Prisma, "
    "frontend Next.js, deploy Docker/Terraform (AWS eu-west-1)."
)

STACK = [
    ("Backend", "TypeScript 5.3 / Node.js 18 LTS / Express 4.18"),
    ("ORM / DB", "Prisma 5.6 (PostgreSQL 15)"),
    ("Autenticacao", "JWT RS256 (JWKS) + RBAC custom (roles: admin, member)"),
    ("Frontend", "Next.js 13.4 (App Router) + React 18 + Tailwind"),
    ("Sanitizacao", "DOMPurify presente no package.json, NAO aplicado"),
    ("Deploy / IaC", "Docker + docker-compose + Terraform (AWS eu-west-1) + GitHub Actions"),
    ("Dados pessoais", "PII: email, nome, notas, activity log, health form (Art. 9), telemetria"),
    ("Terceiros", "PostHog (analytics), Sentry (crash), Resend (e-mail), Cloudflare (CDN)"),
]

CATEGORIES = [
    (1, "Banco sem tranca (isolamento)"),
    (2, "Permissao definida no navegador"),
    (3, "IDOR"),
    (4, "Chaves expostas"),
    (5, "Inputs sem tratamento (XSS)"),
    (6, "Autenticacao e sessoes"),
    (7, "SSRF"),
    (8, "Integridade de escrita (CSRF/path/upload)"),
    (9, "Rate limiting e forca bruta"),
    (10, "Dependencias e IaC"),
    (11, "Vazamento de informacao"),
    (12, "Compliance RGPD"),
]

SHORT_CAT = {
    1: "Isolamento",
    2: "Permissao UI",
    3: "IDOR",
    4: "Chaves",
    5: "XSS",
    6: "Auth",
    7: "SSRF",
    8: "Escrita",
    9: "Rate lim.",
    10: "Dep./IaC",
    11: "Disclosure",
    12: "RGPD",
}

MATURITY = [
    (1, "Banco sem tranca (isolamento)", 55),
    (2, "Permissao definida no navegador", 40),
    (3, "IDOR", 35),
    (4, "Chaves expostas", 60),
    (5, "Inputs sem tratamento (XSS)", 65),
    (6, "Autenticacao e sessoes", 30),
    (7, "SSRF", 50),
    (8, "Integridade de escrita (CSRF/path/upload)", 45),
    (9, "Rate limiting e forca bruta", 40),
    (10, "Dependencias e IaC", 55),
    (11, "Vazamento de informacao", 50),
    (12, "Compliance RGPD", 60),
]

FINDINGS = [
    dict(
        id="F1", cat=1, versions=["security", "rgpd"], severity="critica",
        file="apps/api/src/routes/notes.ts", line=42, cwe="CWE-639", owasp="A01:2021",
        desc="Listagem de notas nao filtra por spaceId/usuario: devolve todas as notas de todos os espacos.",
        code="const notes = await prisma.note.findMany({});  // sem filtro de tenant",
        why="Qualquer usuario autenticado lista notas de outros inquilinos ao chamar GET /api/notes.",
        impact="Exposicao transversal de dados (cross-tenant) de todos os clientes.",
        fix="Injetar scope obrigatorio: prisma.note.findMany({ where: { spaceId: session.spaceId } }).",
        accept=["GET /api/notes retorna 0 notas de outros spaces", "Teste com 2 contas em spaces distintos"],
        heat=(5, 2),
    ),
    dict(
        id="F2", cat=1, versions=["security", "rgpd"], severity="alta",
        file="apps/api/src/routes/team.ts", line=88, cwe="CWE-639", owasp="A01:2021",
        desc="Exportacao CSV de atividade agrega registros de todos os tenants sem WHERE por inquilino.",
        code="SELECT * FROM activity WHERE space_id = ANY(...)  // agrega todos",
        why="O endpoint /api/teams/export recebe ?spaceIds= e nao valida pertencimento de cada id.",
        impact="Exfiltracao de dados de atividade (PII) de outras organizacoes.",
        fix="Validar pertencimento de cada spaceId antes de agregar; adicionar filtro de tenant no SQL.",
        accept=["Export contendo espaco de outro tenant retorna erro", "Query SQL final tem WHERE tenant_id"],
        heat=(4, 2),
    ),
    dict(
        id="F3", cat=2, versions=["security", "rgpd"], severity="critica",
        file="apps/web/src/pages/settings/TeamSettings.tsx", line=15, cwe="CWE-862", owasp="A01:2021",
        desc="O botao de excluir time fica escondido para nao-admins na UI, mas DELETE /api/teams/:id nao valida papel.",
        code="{isAdmin && <DeleteTeamButton/>}  // gate apenas na UI",
        why="apps/api/src/routes/team.ts:120 registra router.delete('/:id', auth, handler) sem requireRole('admin').",
        impact="Qualquer membro pode excluir/alterar configuracoes do time (escrita privilegiada).",
        fix="Adicionar middleware de autorizacao requireRole('admin') em todas as mutacoes de team.",
        accept=["DELETE sem papel admin retorna 403", "Teste automatizado cobre rota com role member"],
        heat=(5, 2),
    ),
    dict(
        id="F4", cat=3, versions=["security", "rgpd"], severity="critica",
        file="apps/api/src/routes/notes.ts", line=66, cwe="CWE-639", owasp="A01:2021",
        desc="Exclusao de nota por ID sem verificar se a nota pertence ao usuario/space do chamador.",
        code="router.delete('/:id', auth, async (req, res) => { await prisma.note.delete({ where: { id } }); });",
        why="Nao ha where:{ ownerId } nem verificacao de posse antes do delete.",
        impact="Delecao/IDOR: qualquer usuario apaga recursos de qualquer outro usuario.",
        fix="Buscar nota com ownerId do token; 404/403 se nao pertencer; excluir com where composto.",
        accept=["Deletar nota alheia retorna 404", "Notas de outros users permanecem no banco"],
        heat=(5, 2),
    ),
    dict(
        id="F5", cat=3, versions=["security", "rgpd"], severity="alta",
        file="apps/api/src/routes/team.ts", line=55, cwe="CWE-639", owasp="A01:2021",
        desc="Lista de membros de um time sem validar que o chamador pertence ao time.",
        code="router.get('/:teamId/members', auth, async (req, res) => { ... });",
        why="apps/api/src/middleware/team.ts valida posse apenas em GET /api/teams/:id, nao no sub-recurso members.",
        impact="Vazamento de PII (nomes/e-mails de membros) de times privados de outras empresas.",
        fix="Aplicar middleware de membership no sub-recurso /:teamId/* com verificacao de posse.",
        accept=["GET members de time alheio retorna 403", "Middleware aplicado a todas as rotas /:teamId/*"],
        heat=(4, 3),
    ),
    dict(
        id="F6", cat=4, versions=["security", "rgpd"], severity="alta",
        file="docker-compose.yml", line=12, cwe="CWE-798", owasp="A07:2021",
        desc="Segredo de assinatura JWT com default publico e sem validacao de startup que rejeite o default.",
        code="JWT_SECRET=${JWT_SECRET:-dev-secret-notely}  # default publico",
        why="Se JWT_SECRET nao for injetado, producao assina tokens com 'dev-secret-notely' conhecido.",
        impact="Forjar tokens JWT e acessar qualquer conta com papel admin.",
        fix="Remover default; falhar no boot se a env nao existir; usar secrets manager.",
        accept=["Boot falha sem JWT_SECRET", "gitleaks nao encontra o default no repo"],
        heat=(4, 2),
    ),
    dict(
        id="F7", cat=4, versions=["security", "rgpd"], severity="alta",
        file="apps/api/.env (git history, commit a1b2c3d)", line=1, cwe="CWE-798", owasp="A07:2021",
        desc="Chave real de producao commitada em .env e removida depois; ainda acessivel no git history.",
        code="STRIPE_API_KEY=sk_live_51N3x...  // removida do HEAD mas presente no historico",
        why="gitleaks localizou a chave no commit a1b2c3d; quem tiver acesso ao repo pode extraí-la.",
        impact="Fraude/comprometimento de pagamentos; chave precisa ser rotacionada.",
        fix="Rotacionar chave; purgar historico (filter-repo); adicionar gitleaks no pre-commit e CI.",
        accept=["Chave revogada na Stripe", "gitleaks limpo no reflog/historico filtrado"],
        heat=(3, 2),
    ),
    dict(
        id="F8", cat=5, versions=["security", "rgpd"], severity="alta",
        file="apps/web/src/components/NoteContent.tsx", line=9, cwe="CWE-79", owasp="A03:2021",
        desc="Conteudo de nota (HTML do usuario) renderizado sem sanitizacao apesar de DOMPurify estar no package.json.",
        code="<div dangerouslySetInnerHTML={{ __html: note.content }} />  // sem DOMPurify",
        why="Outro usuario pode criar nota com <img src=x onerror=alert(document.cookie)>.",
        impact="XSS persistente entre usuarios (roubo de sessao, execucao no contexto admin).",
        fix="Sanitizar com DOMPurify no client e com lib equivalente no servidor antes de persistir.",
        accept=["Payload XSS nao renderiza script", "DOMPurify aplicado ao render"],
        heat=(4, 3),
    ),
    dict(
        id="F9", cat=5, versions=["security", "rgpd"], severity="media",
        file="apps/api/src/services/mailer.ts", line=31, cwe="CWE-80", owasp="A03:2021",
        desc="Nome do usuario interpolado em e-mail HTML sem escape/espacao.",
        code="`<p>Ola, ${user.name}</p>`  // interpolacao sem escape",
        why="Nome controlado por usuario com <b>/<script> quebra o template e pode virar phishing/XSS no cliente de e-mail.",
        impact="Phishing direcionado e injecao em template de e-mail.",
        fix="Escape de HTML ou uso de template engine com autoescape para campos do usuario.",
        accept=["Nome com <script> e exibido literalmente", "Teste unitario do template"],
        heat=(3, 4),
    ),
    dict(
        id="F10", cat=6, versions=["security", "rgpd"], severity="critica",
        file="apps/api/src/lib/password.ts", line=8, cwe="CWE-916", owasp="A02:2021",
        desc="Senhas armazenadas com SHA-256 simples, sem salt e sem algoritmo de derivacao lento.",
        code="crypto.createHash('sha256').update(pw).digest('hex')  // hash sem sal e rapido",
        why="Banco vazado permite brute-force offline imediato de senhas (sem custo computacional).",
        impact="Comprometimento em massa de contas com senhas recuperaveis.",
        fix="Migrar para argon2id/bcrypt com salt por usuario; rehash em login.",
        accept=["Nenhuma senha SHA-256 em repouso", "Migracao backfill executada e verificada"],
        heat=(4, 1),
    ),
    dict(
        id="F11", cat=6, versions=["security", "rgpd"], severity="media",
        file="apps/api/src/routes/auth.ts", line=40, cwe="CWE-287", owasp="A07:2021",
        desc="Login de administradores sem exigencia de segundo fator.",
        code="router.post('/login', loginHandler)  // sem MFA/2FA",
        why="Credenciais vazadas (F6/F10) bastam para acesso admin; nao ha TOTP/WebAuthn.",
        impact="Account takeover de administradores com impacto total no produto.",
        fix="Exigir MFA para funcoes privilegiadas (admin, suporte) e eventos sensiveis.",
        accept=["Admin sem 2FA nao acessa area administrativa", "Configuracao de MFA documentada"],
        heat=(3, 3),
    ),
    dict(
        id="F12", cat=6, versions=["security", "rgpd"], severity="alta",
        file="apps/api/src/routes/auth.ts", line=120, cwe="CWE-640", owasp="A07:2021",
        desc="Token de reset de senha numerico de 6 digitos sem tentativa de limite/rate limit.",
        code="token = Math.floor(100000 + Math.random()*900000)  // 6 digitos, 5 min",
        why="Espaco de 1e6 combinacoes; forca bruta online (categoria 9) viabiliza takeover.",
        impact="Account takeover via reset de senha.",
        fix="Token aleatorio de alta entropia, expiracao, invalidacao pos-uso e limitacao de tentativas.",
        accept=["Reset com token errado bloqueia apos 5 tentativas", "Token e UUID/256 bits"],
        heat=(4, 2),
    ),
    dict(
        id="F13", cat=7, versions=["security", "rgpd"], severity="alta",
        file="apps/api/src/services/import.ts", line=33, cwe="CWE-918", owasp="A10:2021",
        desc="URL de usuario buscada pelo servidor (preview de link) sem allowlist/denylist de hosts, sem bloqueio de IP interno e seguindo redirects.",
        code="const resp = await fetch(userUrl);  // preview de link, sem allowlist",
        why="SSRF: URL pode apontar para 169.254.169.254 (metadata AWS) ou servicos internos; resposta pode ser refletida ao usuario.",
        impact="Acesso ao metadata da nuvem e a servicos internos; exfiltracao via resposta.",
        fix="Allowlist de dominios, bloqueio de IPs internos/link-local, proibicao de redirects, timeout e validacao de protocolo.",
        accept=["URL para 169.254.169.254 bloqueada", "Redirect a IP interno bloqueado"],
        heat=(4, 2),
    ),
    dict(
        id="F14", cat=8, versions=["security", "rgpd"], severity="media",
        file="apps/api/src/routes/webhook.ts", line=19, cwe="CWE-352", owasp="A01:2021",
        desc="Cookies de API com SameSite=None e mutacoes sem token CSRF nem verificacao de Origin.",
        code="app.use(cors({ origin: true, credentials: true }))  // cookies SameSite=None",
        why="Sites maliciosos podem disparar mutacoes cross-origin com credenciais do usuario (CSRF).",
        impact="Acoes nao autorizadas em nome do usuario (CSRF).",
        fix="Restringir CORS a origem confiavel, SameSite=Lax/Strict e validar Origin/CSRF token em mutacoes.",
        accept=["Requisicao cross-origin sem token retorna 403", "cors() com origem permitida explicita"],
        heat=(3, 4),
    ),
    dict(
        id="F15", cat=8, versions=["security", "rgpd"], severity="alta",
        file="apps/api/src/routes/import.ts", line=60, cwe="CWE-22", owasp="A01:2021",
        desc="Nome de arquivo enviado pelo usuario interpolado no caminho sem normalizacao nem validacao de conteudo.",
        code="const dest = path.join(UPLOAD_DIR, file.originalname);",
        why="originalname pode conter ../../ e sobrescrever arquivos arbitrarios (path traversal / zip-slip).",
        impact="Escrita arbitraria no servidor; potencial RCE via configuracao sobrescrita.",
        fix="Gerar nome aleatorio, validar tipo por conteudo (sniffing), limite de tamanho e armazenar fora da raiz publica.",
        accept=["Upload com ../../ nao escreve fora do diretorio", "HTML/SVG com script rejeitado"],
        heat=(4, 2),
    ),
    dict(
        id="F16", cat=9, versions=["security", "rgpd"], severity="alta",
        file="apps/api/src/routes/auth.ts", line=12, cwe="CWE-307", owasp="A07:2021",
        desc="Endpoints de login/reset sem rate limiting no codigo (depende de nginx com limite fixo nao documentado).",
        code="router.post('/login', loginHandler)  // sem rate limit no app",
        why="A categoria 12 (token de reset) e brutavel e credenciais podem ser testadas em massa.",
        impact="Brute force e credential stuffing contra contas.",
        fix="Rate limit por IP e por conta com backoff exponencial; lockout temporario.",
        accept=["10 falhas de login por conta/IP bloqueiam por 15 min", "Teste automatizado de rate limit"],
        heat=(4, 3),
    ),
    dict(
        id="F17", cat=10, versions=["security", "rgpd"], severity="media",
        file="package.json", line=45, cwe="CWE-1035", owasp="A06:2021",
        desc="Dependencia com CVE alcancavel e imagem base sem pin, ambas alem da politica de EOL.",
        code='"next": "13.4.19"  // CVE-2023-44487 (HTTP/2 DoS); Dockerfile: FROM node:18 (latest)',
        why="next@13.4.19 possui CVE conhecida; FROM node:18 sem tag especifica instala versoes imprevisiveis.",
        impact="DoS e builds nao reproduziveis com superficie de vulnerabilidades desconhecida.",
        fix="Atualizar dependencias, pin de imagem base com digest, habilitar Dependabot/CI de auditoria.",
        accept=["npm audit sem criticas", "Imagem base com digest fixado"],
        heat=(2, 2),
    ),
    dict(
        id="F18", cat=10, versions=["security", "rgpd"], severity="alta",
        file="terraform/main.tf", line=22, cwe="CWE-269", owasp="A01:2021",
        desc="Bucket S3 de exportacoes criado com ACL publica.",
        code='acl = "public-read"  # bucket de exportacoes',
        why="Exportacoes contem PII (relatorio CSV, categoria 1) e ficam legiveis publicamente.",
        impact="Vazamento publico de dados de clientes.",
        fix="Remover ACL publica, usar private + bucket policy restrita, verificar com checkov no CI.",
        accept=["Bucket sem ACL publica", "checkov limpo para o modulo de storage"],
        heat=(3, 2),
    ),
    dict(
        id="F19", cat=11, versions=["security", "rgpd"], severity="media",
        file="apps/api/src/app.ts", line=10, cwe="CWE-209", owasp="A04:2021",
        desc="Stack trace completo em respostas de erro em producao e ausencia de headers de seguranca (CSP, HSTS).",
        code="app.use((err, req, res, next) => res.status(500).json({ error: err.stack }))  // + sem helmet",
        why="Detalhes internos e versoes auxiliam atacantes; sem CSP o XSS da categoria 5 amplifica.",
        impact="Reconhecimento facilitado e mitigacao de XSS prejudicada.",
        fix="Erros genericos em producao, helmet/secureHeaders com CSP e HSTS.",
        accept=["Resposta 500 nao contem stack", "Headers de seguranca presentes"],
        heat=(3, 3),
    ),
    dict(
        id="R1", cat=12, versions=["rgpd"], severity="media",
        file="apps/web/src/components/forms/SignupForm.tsx", line=12, cwe="CWE-359", owasp="A04:2021",
        desc="Checkbox de marketing pre-marcada e sem registro de consentimento (timestamp, versao, finalidade).",
        code='<input type="checkbox" checked={true} /> Marketing',
        why="RGPD Art. 7 exige opt-in explicito, nao pre-marcado, e registro auditavel do consentimento.",
        impact="Base legal de marketing invalida; risco de sancao (ate 4% do faturamento global).",
        fix="Opt-in desmarcado por padrao; persistir consentimento (quem, quando, versao, finalidade) e fluxo de retirada.",
        accept=["Checkbox desmarcada por padrao", "Tabela consent_log populada ao salvar"],
        rgpd=True, rgpd_art="Art. 7", heat=(3, 4),
    ),
    dict(
        id="R2", cat=12, versions=["rgpd"], severity="alta",
        file="apps/api/src/routes/users.ts", line=77, cwe="CWE-359", owasp="A04:2021",
        desc="'Excluir conta' so marca deletedAt: notas, activity, backups e logs continuam armazenando dados pessoais.",
        code="user.deletedAt = new Date();  // soft-delete apenas; notas/activity/backups ficam",
        why="RGPD Art. 17 exige apagamento efetivo; soft-delete nao atende ao direito ao esquecimento.",
        impact="Direito de apagamento inaplicavel; dados permanecem sob controle do controlador sem base.",
        fix="Apagar/anonimizar dados em cascata (tabelas, cache, logs, backups) ou anonimizacao irreversivel.",
        accept=["Apos exclusao, dados do usuario ausentes em todas as tabelas", "Backup restaurado nao contem PII ativa"],
        rgpd=True, rgpd_art="Art. 17", heat=(4, 3),
    ),
    dict(
        id="R3", cat=12, versions=["rgpd"], severity="media",
        file="apps/api/src/middleware/logger.ts", line=9, cwe="CWE-212", owasp="A09:2021",
        desc="Logs registram corpo completo de requisicoes contendo e-mail/CPF, sem expiracao.",
        code="logger.info('request', req.body)  // loga e-mail e corpo inteiro",
        why="Minimizacao (Art. 5(1)(c)) e retencao (Art. 5(1)(e)) violadas; logs sao coleta desnecessaria.",
        impact="Retencao de PII sem prazo; aumento de superficie em caso de vazamento de logs.",
        fix="Logar apenas metadados (id, rota, status), mascarar PII e aplicar retencao automatica.",
        accept=["Log nao contem corpo da requisicao", "Rotacao de logs com TTL configurada"],
        rgpd=True, rgpd_art="Art. 5", heat=(3, 4),
    ),
    dict(
        id="R4", cat=12, versions=["rgpd"], severity="media",
        file="apps/web/src/lib/analytics.ts", line=5, cwe="CWE-359", owasp="A04:2021",
        desc="Script de analytics (PostHog) carregado na primeira pagina sem banner/consentimento previo.",
        code="posthog.init('phc_xxx', { load: () => track_all() })  // carrega antes do consentimento",
        why="Cookies nao essenciais nao podem ser instalados antes de consentimento (ePrivacy/Art. 7).",
        impact="Rastreamento sem base legal; multa por cookies nao consentidos.",
        fix="Banner de cookies com gestao de preferencias; carregar trackers apenas apos opt-in.",
        accept=["Analytics nao inicia sem consentimento", "Preferencia de cookies persistida e reutilizada"],
        rgpd=True, rgpd_art="Art. 7", heat=(3, 3),
    ),
    dict(
        id="R5", cat=12, versions=["rgpd"], severity="baixa",
        file="apps/api/src/lib/expunge.ts", line=1, cwe="CWE-212", owasp="A04:2021",
        desc="Politica de retencao documentada, mas nenhum job de expurgo/expiracao implementado.",
        code="// TODO: job de expurgo nao implementado",
        why="Art. 5(1)(e): dados nao podem ser mantidos indefinidamente sem prazo.",
        impact="Acumulo de dados alem do necessario; risco incremental.",
        fix="Implementar job agendado de expurgo por idade e categoria, com metricas e alerta.",
        accept=["Job executa em staging e apaga registros vencidos", "Retencao configuravel por categoria"],
        rgpd=True, rgpd_art="Art. 5", heat=(3, 5),
    ),
    dict(
        id="R6", cat=12, versions=["rgpd"], severity="baixa",
        file="apps/web/src/app/privacy/page.tsx", line=3, cwe="CWE-359", owasp="A04:2021",
        desc="Politica de privacidade desatualizada e contradiz o que o codigo realmente faz (terceiros reais).",
        code="'Nao compartilhamos dados com terceiros'  // contradiz PostHog/Sentry/Resend",
        why="Art. 12-13 exigem informacao precisa; inconsistencia gera risco de enforcement e dano reputacional.",
        impact="Informacao enganosa ao titular; sancao por transparencia.",
        fix="Revisar politica com inventario real de dados, finalidades, terceiros e direitos.",
        accept=["Politica lista todos os processadores reais", "Data de revisao atualizada"],
        rgpd=True, rgpd_art="Art. 12-13", heat=(2, 5),
    ),
    dict(
        id="R7", cat=12, versions=["rgpd"], severity="alta",
        file="apps/web/src/components/forms/HealthForm.tsx", line=7, cwe="CWE-359", owasp="A04:2021",
        desc="Coleta de dados sensiveis (saude) como dado comum, sem consentimento explicito nem finalidade especifica.",
        code="// coleta condicoes de saude sem base legal especifica (Art. 9)",
        why="Art. 9 proibe tratamento de categorias especiais sem base propria; falha gera multa maxima.",
        impact="Tratamento ilicito de dados sensiveis; alto risco a direitos fundamentais.",
        fix="Consentimento explicito e destacado, minimizacao, DPIA e armazenamento com protecao adicional.",
        accept=["Campo de saude bloqueado sem consentimento explicito", "DPIA documentada para o modulo"],
        rgpd=True, rgpd_art="Art. 9", heat=(4, 3),
    ),
    dict(
        id="R8", cat=12, versions=["rgpd"], severity="media",
        file="apps/api/src/services/score.ts", line=22, cwe="CWE-359", owasp="A04:2021",
        desc="Pontuacao de credito/risco gerada por modelo sem fluxo de intervencao humana, explicacao ou revisao.",
        code="score = model.predict(features(user))  // decisao automatizada sem revisao humana",
        why="Art. 22: decisao automatizada com efeitos significativos exige direito a intervencao humana e explicacao.",
        impact="Titulares sem recurso efetivo contra decisoes automatizadas.",
        fix="Prever endpoint de revisao humana, explicacao e contestacao da decisao.",
        accept=["Titular pode solicitar revisao humana", "Decisao expoe explicacao ao titular"],
        rgpd=True, rgpd_art="Art. 22", heat=(3, 4),
    ),
]

STRENGTHS = [
    (
        "apps/api/src/middleware/auth.ts:14 - Middleware de autenticacao valida assinatura RS256, expiracao e emissor (JWKS) e e aplicado em todas as rotas sob /api.",
        "Categoria 2/3: a autenticacao em si esta correta; o problema sao as rotas que a ignoram.",
        ["security", "rgpd"],
    ),
    (
        "apps/web/src/lib/session.ts:22 - Cookies de sessao com HttpOnly, Secure e SameSite=Lax.",
        "Mitiga roubo de sessao por XSS (parcialmente, ate a categoria 5 ser corrigida).",
        ["security", "rgpd"],
    ),
    (
        "apps/api/src/routes/notes.ts:21 - Inputs de criacao de nota validados com schema zod (tamanho e tipo).",
        "Categoria 5: reduz a superficie de injecao estrutural.",
        ["security", "rgpd"],
    ),
    (
        "apps/api/src/middleware/team.ts:31 - GET /api/teams/:id valida pertencimento do chamador ao time.",
        "Categoria 3: padrao correto a ser replicado nos sub-recursos.",
        ["security", "rgpd"],
    ),
    (
        "terraform/main.tf:41 - Volumes de banco criados com encryption_at_rest habilitado (AWS KMS).",
        "RGPD Art. 32: criptografia em repouso dos dados pessoais.",
        ["rgpd"],
    ),
    (
        "docs/incidentes/runbook.md - Runbook de resposta a incidente com notificacao a autoridade em ate 72h e registro de violacoes.",
        "RGPD Art. 33-34: processo documentado.",
        ["rgpd"],
    ),
]

WEAKNESSES_SECURITY = [
    "Isolamento e posse fragilizados: rotas de listagem/exclusao/exportacao operam sem escopo de tenant ou dono (F1, F2, F4, F5).",
    "Autorizacao fragil: papel validado apenas na UI e nao no servidor em acoes privilegiadas (F3).",
    "Gestao de credenciais precaria: senhas SHA-256, secrets com default publico e chave real no historico git (F6, F7, F10).",
]

WEAKNESSES_RGPD = WEAKNESSES_SECURITY + [
    "Conformidade RGPD incompleta: consentimento invalido, exclusao soft-only, rastreamento sem opt-in e retencao indefinida (R1-R5).",
]

RGPD_PANEL = [
    ("12.1", "Base legal e consentimento (Art. 6, 7)", "nao conformidade", "SignupForm.tsx:12"),
    ("12.2", "Cookies e rastreamento (ePrivacy)", "nao conformidade", "analytics.ts:5"),
    ("12.3", "Direitos dos titulares (Art. 15-22)", "nao conformidade", "users.ts:77"),
    ("12.4", "Minimizacao e retencao (Art. 5(1)(c),(e))", "nao conformidade", "logger.ts:9 / expunge.ts:1"),
    ("12.5", "Seguranca e pseudonimizacao (Art. 32)", "em conformidade", "TLS 1.2+, KMS em repouso"),
    ("12.6", "Transferencias internacionais (Art. 44-49)", "em conformidade", "eu-west-1 + SCC"),
    ("12.7", "Processadores e terceiros (Art. 28)", "nao verificada", "Sem DPA com Resend"),
    ("12.8", "Notificacao de violacao (Art. 33-34)", "em conformidade", "runbook.md"),
    ("12.9", "Privacidade por design e DPIA (Art. 25, 35)", "em conformidade", "Perfis privados por padrao"),
    ("12.10", "Politica de privacidade (Art. 12-13)", "nao conformidade", "privacy/page.tsx:3"),
    ("12.11", "Menores (Art. 8)", "nao aplicavel", "B2B"),
    ("12.12", "PII em locais indevidos", "nao verificada", "Bundle nao rastreado"),
    ("12.13", "Dados sensiveis (Art. 9)", "nao conformidade", "HealthForm.tsx:7"),
    ("12.14", "Decisao automatizada e perfilagem (Art. 22)", "nao conformidade", "score.ts:22"),
    ("12.15", "Trilha de auditoria de acesso a PII", "nao conformidade", "lib/audit.ts vazio"),
    ("12.16", "Canais nao-code de exercicio de direitos", "em conformidade", "privacidade@notely.app + SLA 30d"),
]

IDOR_MATRIX = [
    ("/api/notes", "GET", "spaceId (implicit)", "NAO", "notes.ts:42 (F1)"),
    ("/api/notes/:id", "DELETE", "id", "NAO", "notes.ts:66 (F4)"),
    ("/api/teams/:id", "GET", "id", "SIM", "middleware/team.ts:31"),
    ("/api/teams/:id/members", "GET", "teamId", "NAO", "team.ts:55 (F5)"),
    ("/api/teams/:id", "DELETE", "id", "NAO (RBAC)", "team.ts:120 (F3)"),
    ("/api/teams/export", "GET", "spaceIds[]", "NAO", "team.ts:88 (F2)"),
    ("/api/auth/login", "POST", "-", "n.a.", "auth.ts:12 (F16)"),
    ("/api/users/me", "DELETE", "me", "SIM", "users.ts:77 (R2)"),
]

UI_GATES = [
    ("isAdmin (DeleteTeamButton)", "TeamSettings.tsx:15", "DELETE /api/teams/:id", "NAO (F3)"),
    ("isAdmin (TeamSettings menu)", "TeamSettings.tsx:8", "PUT /api/teams/:id", "NAO"),
    ("isOwner (NoteMenu)", "NoteMenu.tsx:20", "DELETE /api/notes/:id", "NAO (F4)"),
    ("role==='member' (view)", "TeamPage.tsx:5", "GET /api/teams/:id/members", "NAO (F5)"),
]

SCANS = [
    ("gitleaks", "git history", "14", "3", "1 (F7)"),
    ("npm audit", "package-lock.json", "5", "2", "1 (F17)"),
    ("trivy", "Dockerfile", "8", "2", "1 (F17)"),
    ("checkov", "terraform/", "6", "2", "1 (F18)"),
    ("bundle scan", "dist/", "2", "0", "0"),
]

SBOM = [
    ("next", "13.4.19", "CVE-2023-44487 (media)", "-"),
    ("express", "4.18.2", "Sem CVE critica", "-"),
    ("argon2", "nao presente", "SUBSTITUIR SHA-256 (F10)", "-"),
    ("imagem base node", "18 (latest)", "Sem pin/digest (F17)", "-"),
    ("PostHog", "SDK web", "Carregado sem consentimento (R4)", "Sim"),
    ("Sentry", "SDK web", "OK", "Sim"),
    ("Resend", "e-mail transacional", "Sem DPA assinado (12.7)", "Nao"),
    ("Cloudflare", "CDN", "OK", "Sim"),
]

GLOSSARY = [
    ("CWE-639", "Autorizacao de acesso a recursos por ID nao confiavel (IDOR)"),
    ("CWE-862", "Autorizacao ausente"),
    ("CWE-798", "Uso de credenciais hardcoded"),
    ("CWE-79", "Cross-Site Scripting"),
    ("CWE-916", "Uso de hash fraco para senha"),
    ("CWE-918", "SSRF"),
    ("CWE-352", "CSRF"),
    ("CWE-22", "Path traversal"),
    ("CWE-307", "Restricao inadequada de tentativas"),
    ("CWE-209", "Exposicao de informacao sensivel via mensagem de erro"),
    ("CWE-359", "Exposicao de informacao privada"),
    ("RGPD Art. 7", "Condicoes do consentimento"),
    ("RGPD Art. 9", "Dados sensiveis (categorias especiais)"),
    ("RGPD Art. 17", "Direito ao apagamento"),
    ("RGPD Art. 22", "Decisao automatizada"),
    ("RGPD Art. 32", "Seguranca do tratamento"),
    ("RGPD Art. 33-34", "Notificacao de violacao"),
]

LIMITS = [
    "Nenhum teste ativo de rede, forca bruta ou exploracao fora do ambiente local de desenvolvimento.",
    "Analise majoritariamente estatica; PoCs de alta/critica nao executadas contra ambiente real.",
    "Nao verificada a integridade de backups fisicos (restauracao) nem a configuracao do provedor de e-mail.",
    "A superficie de terceiros (12.7) depende de DPA que nao esta no repositorio.",
]

ISSUE_GROUPS = [
    ["R1", "R4"],
    ["R3", "R5"],
    ["F1"], ["F2"], ["F3"], ["F4"], ["F5"], ["F6"], ["F7"], ["F8"], ["F9"],
    ["F10"], ["F11"], ["F12"], ["F13"], ["F14"], ["F15"], ["F16"], ["F17"],
    ["F18"], ["F19"], ["R2"], ["R6"], ["R7"], ["R8"],
]
